-- MySQL Script generated by MySQL Workbench
-- Sun Aug 23 21:35:39 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`CORTES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CORTES` (
  `Niños-Niñas` INT NOT NULL,
  `Mujeres` VARCHAR(45) NULL,
  `Hombres` VARCHAR(45) NULL,
  PRIMARY KEY (`Niños-Niñas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`MAQUILLAJE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`MAQUILLAJE` (
  `Maquillaje social` INT NOT NULL,
  `Maquillaje artistico` VARCHAR(45) NULL,
  PRIMARY KEY (`Maquillaje social`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CONTACTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CONTACTO` (
  `ID Contactos` INT NOT NULL,
  PRIMARY KEY (`ID Contactos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PAGOS AGENDA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PAGOS AGENDA` (
  `ID pagos` INT NOT NULL,
  `Confirmacion de cita` VARCHAR(45) NULL,
  `Confirmacion de pago` VARCHAR(45) NULL,
  `CONTACTO_ID Contactos` INT NOT NULL,
  PRIMARY KEY (`ID pagos`, `CONTACTO_ID Contactos`),
  INDEX `fk_PAGOS AGENDA_CONTACTO1_idx` (`CONTACTO_ID Contactos` ASC) VISIBLE,
  CONSTRAINT `fk_PAGOS AGENDA_CONTACTO1`
    FOREIGN KEY (`CONTACTO_ID Contactos`)
    REFERENCES `mydb`.`CONTACTO` (`ID Contactos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PAGOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PAGOS` (
  `ID pagos` INT NOT NULL,
  `Nequi` VARCHAR(45) NULL,
  `Targetas de credito` VARCHAR(45) NULL,
  `PAGOS AGENDA_ID pagos` INT NOT NULL,
  PRIMARY KEY (`ID pagos`, `PAGOS AGENDA_ID pagos`),
  INDEX `fk_PAGOS_PAGOS AGENDA1_idx` (`PAGOS AGENDA_ID pagos` ASC) VISIBLE,
  CONSTRAINT `fk_PAGOS_PAGOS AGENDA1`
    FOREIGN KEY (`PAGOS AGENDA_ID pagos`)
    REFERENCES `mydb`.`PAGOS AGENDA` (`ID pagos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TIPOS DE SERVICIOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TIPOS DE SERVICIOS` (
  `ID Servicios` INT NOT NULL,
  `semipermanente-gel-acrilicas-tradic` VARCHAR(45) NULL,
  `Cortes dama-caballero-niñios` VARCHAR(45) NULL,
  `Cejas depilacion-henna-micropigmentacion` VARCHAR(45) NULL,
  `Pestañas 3D-4D-Ojo de gato` VARCHAR(45) NULL,
  `Maquillaje social-Artistico` VARCHAR(45) NULL,
  PRIMARY KEY (`ID Servicios`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`SERVICIOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`SERVICIOS` (
  `cortes` INT NOT NULL,
  `Uñas` VARCHAR(45) NULL,
  `Maquillaje` VARCHAR(45) NULL,
  `Cejas-Pestañas` VARCHAR(45) NULL,
  `PAGOS_ID pagos` INT NOT NULL,
  `TIPOS DE SERVICIOS_ID Servicios` INT NOT NULL,
  PRIMARY KEY (`cortes`, `PAGOS_ID pagos`),
  INDEX `fk_SERVICIOS_PAGOS1_idx` (`PAGOS_ID pagos` ASC) VISIBLE,
  INDEX `fk_SERVICIOS_TIPOS DE SERVICIOS1_idx` (`TIPOS DE SERVICIOS_ID Servicios` ASC) VISIBLE,
  CONSTRAINT `fk_SERVICIOS_PAGOS1`
    FOREIGN KEY (`PAGOS_ID pagos`)
    REFERENCES `mydb`.`PAGOS` (`ID pagos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SERVICIOS_TIPOS DE SERVICIOS1`
    FOREIGN KEY (`TIPOS DE SERVICIOS_ID Servicios`)
    REFERENCES `mydb`.`TIPOS DE SERVICIOS` (`ID Servicios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PESTAÑAS Y CEJAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PESTAÑAS Y CEJAS` (
  `Pestañas 3D-4D-Ojo de gato` INT NOT NULL,
  `cejas Depilacion-Henna-Microblading` VARCHAR(45) NULL,
  PRIMARY KEY (`Pestañas 3D-4D-Ojo de gato`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`SESION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`SESION` (
  `ID Inicio de sesion` INT NOT NULL,
  `Nombre-Apellido` VARCHAR(45) NULL,
  `Telefono` VARCHAR(45) NULL,
  `Correo electronico` VARCHAR(45) NULL,
  `SERVICIOS_cortes` INT NOT NULL,
  `CONTACTO_ID Contactos` INT NOT NULL,
  PRIMARY KEY (`ID Inicio de sesion`, `SERVICIOS_cortes`, `CONTACTO_ID Contactos`),
  INDEX `fk_SESION_SERVICIOS1_idx` (`SERVICIOS_cortes` ASC) VISIBLE,
  INDEX `fk_SESION_CONTACTO1_idx` (`CONTACTO_ID Contactos` ASC) VISIBLE,
  CONSTRAINT `fk_SESION_SERVICIOS1`
    FOREIGN KEY (`SERVICIOS_cortes`)
    REFERENCES `mydb`.`SERVICIOS` (`cortes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SESION_CONTACTO1`
    FOREIGN KEY (`CONTACTO_ID Contactos`)
    REFERENCES `mydb`.`CONTACTO` (`ID Contactos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`AGENDA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`AGENDA` (
  `Dia-mes-Hora` INT NOT NULL,
  `Profecional disponible` VARCHAR(45) NULL,
  `Confirmacion de cita` VARCHAR(45) NULL,
  PRIMARY KEY (`Dia-mes-Hora`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PAGO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PAGO` (
  `Nequi` INT NOT NULL,
  `Efectivo` VARCHAR(45) NULL,
  `Targetas de credito` VARCHAR(45) NULL,
  `Confirmacion de pago-resibo` VARCHAR(45) NULL,
  PRIMARY KEY (`Nequi`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CATEGORIAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CATEGORIAS` (
  `ID Categorias` INT NOT NULL,
  `SESION_ID Inicio de sesion` INT NOT NULL,
  PRIMARY KEY (`ID Categorias`),
  INDEX `fk_CATEGORIAS_SESION_idx` (`SESION_ID Inicio de sesion` ASC) VISIBLE,
  CONSTRAINT `fk_CATEGORIAS_SESION`
    FOREIGN KEY (`SESION_ID Inicio de sesion`)
    REFERENCES `mydb`.`SESION` (`ID Inicio de sesion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
